### ISSUE TITLE
Can we make installation process more clear?

### ISSUE THREAD

**Issue by grundic** [yegle/your-dns#6]
Good day,

Thanks for amazing work and sharing it with everyone!
I started to follow the guide, but it was not very strait forward 😞Can we please make it a little bit more clear?
Here are some (dumb) question I've stumbled upon:

- What is `DOMAIN_NAME` in .env file? Shall I register a real NS domain name to be able to use your-dns?
- Could your provide example command how to create free certificate from Let's Encrypt and where it is can be found after generation?
 
Thank you.

**Comment by yegle** [comment]
For `DOMAIN_NAME`, yes you need a real domain name and get a real SSL certificate. Your DNS client, if implemented correctly, will have to verify your server certificate, and you have to own your domain name before you can get a certificate for it.

For getting certificate from Let's Encrypt, I intentionally omitted that part because people usually have their own way of getting a certificate (see the available ACMEv2 clients list: https://letsencrypt.org/docs/client-options/). I found https://russt.me/2018/10/wildcard-certs-w-lets-encrypt-cloudflare/ to be a good example.

**Comment by grundic** [comment]
Awesome, thanks for explanation! 👍

**Comment by yegle** [comment]
FWIW, I've fleshed out the README and various configs. I've followed the guide strictly and started a new DoT/DoH server (your-dns.run).

Please let me know if you still have difficulty following the guide.
